### ISSUE TITLE
Viteless error with rollup

### ISSUE THREAD

**Issue by ericvoshall** [szymmis/vite-express#131]
Hi, I'm pretty new to `vite` + `rollup` so I'm not sure if I'm doing something wrong or misunderstanding something, but I'm attempting to run the app in `vite`-less mode by only installing production dependencies from my `package.json`. I am running the following steps:

1. `npm i`
2. `vite build`
3. `npm ci --omit=dev --ignore-scripts`
4. `NODE_ENV=production tsx src/server/main.ts`

Then I get the following error:

```log
> proj@1.0.0 start
> tsx src/backend/server/main.ts

9:45:27 PM [vite-express] Running in production mode
9:45:27 PM [vite-express] Serving static files from /Users/ev/Git/proj/dist
{"level":"INFO","severity":30,"time":"2024-06-06T01:45:27.413Z","pid":81322,"environment":"backend","module":"server","msg":"[server] Server is listening on http://localhost:3000 "}
/Users/ev/Git/proj/node_modules/rollup/dist/native.js:59
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/ev/Git/proj/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/Users/ev/Git/proj/node_modules/rollup/dist/native.js:68:76)
    ... 8 lines matching cause stack trace ...
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/ev/Git/proj/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Function._ [as _resolveFilename] (/Users/ev/Git/proj/node_modules/tsx/dist/global-require-patch-BGbkqlfk.cjs:1:1674)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/Users/ev/Git/proj/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/Users/ev/Git/proj/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Object.v (/Users/ev/Git/proj/node_modules/tsx/dist/global-require-patch-BGbkqlfk.cjs:1:900)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12)
      at cjsLoader (node:internal/modules/esm/translators:345:17)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
      at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
      at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/ev/Git/proj/node_modules/rollup/dist/native.js'
    ]
  }
}
```

It runs fine with production and dev dependencies installed. I was assuming that after the build step, `vite-express` doesn't need `vite` or `rollup` or any of that since everything has been built.

**Comment by szymmis** [comment]
Hi @ericvoshall. I'm not able to reproduce the bug from the steps that you provided. Have you done anything else apart from the steps? You are right in assuming that `vite` and `rollup` are  not required in so-called `viteless` mode. Thanks in advance for any more info!

**Comment by szymmis** [comment]
Okay, I've actually stumbled upon this issue in one of my repositories. The trivial fix stated in the error message worked for me. Have you tried removing the `package-lock.json` and `node_modules` and then reinstalling the whole thing? Looks like this is a common issue as seen [here](https://github.com/vitejs/vite/discussions/16345) and [here](https://github.com/sveltejs/language-tools/issues/2278).

From my understanding `vite` has some missing dependency and cannot be imported correctly because I wasn't even able to run `npx vite build` so it is clearly not a `vite-express` bug. Also, I haven't got any problems with other package managers such as `yarn` and `bun`.

Tell me if anything here helps.
